config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'payments/outstanding'

  get 'payments/paid'

  root to: 'visitors#home'

  devise_for :users, controllers: { registrations: 'registrations'}

  # landing pages
  get '/about', to: 'visitors#about', as: 'about'
  get '/features', to: 'visitors#features', as: 'features'
  get '/rightmove', to: 'visitors#rightmove', as: 'rightmove'
  get '/vacancies', to: 'visitors#vacancies', as: 'vacancies'
  get '/policy', to: 'visitors#policy', as: 'policy'
  get '/videos', to: 'visitors#videos', as: 'videos'
  get '/pricing', to: 'visitors#pricing', as: 'pricing'
  get '/testimonials', to: 'visitors#testimonials', as: 'testimonials'
  get '/contactus', to: 'visitors#contactus', as: 'contactus'
  post '/contactus', to: 'visitors#send_contactus', as: 'send_contactus'
  get '/instruction', to: 'visitors#instruction', as: 'instruction'

  # dashboard page
  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  # user account pages
  get '/profile', to: 'users#edit', as: 'profile'
  get '/account_summary', to: 'users#show', as: 'account_summary'
  post '/profile', to: 'users#update', as: 'update_profile'

  # properties
  resources :properties

  # connections
  get '/connections/new', to: 'connections#new', as: 'add_connection'
  post '/connections', to: 'connections#create', as: 'create_connection'
  get '/connections', to: 'connections#index', as: 'connections'
  get '/connections/approve/:id', to: 'connections#approve', as: 'approve_connection'
  delete '/connections/:id', to: 'connections#decline', as: 'decline_connection'

  # contracts
  resources :contracts
  get '/active_contracts', to: 'contracts#active_contracts', as: 'active_contracts'
  get '/finished_contracts', to: 'contracts#finished_contracts', as: 'finished_contracts'

  # payments
  get '/payments/outstanding', to: 'payments#outstanding', as: 'outstanding_payments'
  get '/payments/paid', to: 'payments#paid', as: 'paid_payments'
  delete '/payments/:id', to: 'payments#destroy', as: 'payment'
  get '/payments/:return_token/confirm', to: 'payments#confirm', as: 'payment_confirm'
  get '/payments/:id/accept', to: 'payments#accept', as: 'payment_accept'
  get '/payments/:id/refund', to: 'payments#refund', as: 'payment_refund'

  # private payments
  resources :private_payments

  # charges
  resources :charges
  post '/charge_succeed' => 'charges#succeed'

  namespace :api, defaults: {format: :json} do
    resource :auth, controller: :auth, only: [] do
      get :login, on: :collection
    end
    resource :dashboard, controller: :dashboard, only: [] do
      get :counts, on: :collection
    end
    resources :properties, only: [:index]
  end

end

app/controllers/api/dashboard_controller.rb
class Api::DashboardController < Api::ApiController
  before_action :require_user

  def counts
    @user = current_user
    @properties = @user.properties
    @contracts = @user.all_contracts

    @current_year = Date.today.strftime('%Y').to_i
    @current_month = Date.today.strftime('%m').to_i
    @monthly_paid = Date::ABBR_MONTHNAMES[1..12].map {|m| [m, 0]}

    @all_payments = if @user.user_type == User::LANDLORD
                      Payment.year(@current_year)
                      .joins(:contract)
                      .where('contracts.landlord_id = ?', @user.id)
                      .order(:contract_id, :due_date)
                    else
                      Payment.year(@current_year)
                      .joins(:contract)
                      .where('contracts.tenant_id = ?', @user.id)
                      .order(:contract_id, :due_date)
                    end
    @paid_payments = @all_payments.paid.all
    @paid_payments = @paid_payments.group_by { |p| p.date_paid.beginning_of_month }
    @outstanding_payments = @all_payments.outstanding.all + @all_payments.refunded.all
    @outstanding_payments = @outstanding_payments.group_by { |p| p.due_date.beginning_of_month }

    # @year_paid_total = 0
    @paid_payments.sort.map do |month, p|
      index = @monthly_paid.index {|e| e[0] == month.strftime('%b')}
      total = p.map(&:amount).reduce(&:+).to_f
      @monthly_paid[index][1] = total
      # @year_paid_total += total
      @monthly_paid[index][2] = "Amount: #{decimal_amount(total)}"
      @monthly_paid[index][3] = p.count
    end

    render json: {
        properties_count: @properties.count,
        contracts_count: @contracts.count,
        monthly_paid: @monthly_paid[@current_month - 1][3] || 0,
        outstanding_count: @outstanding_payments.count
    }
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :authenticate_user!
  before_filter :check_subscription

  def show
    @user = current_user
    @properties = @user.properties
    @contracts = @user.all_contracts

    @current_year = Date.today.strftime('%Y').to_i
    @current_month = Date.today.strftime('%m').to_i

    @all_payments = if landlord?
                      Payment.year(@current_year)
                      .joins(:contract)
                      .where('contracts.landlord_id = ?', @user.id)
                      .order(:contract_id, :due_date)
                    else
                      Payment.year(@current_year)
                      .joins(:contract)
                      .where('contracts.tenant_id = ?', @user.id)
                      .order(:contract_id, :due_date)
                    end
    # @paid_payments = @all_payments.paid.all + @all_payments.pending.all
    # @paid_payments = @paid_payments.group_by { |p| p.date_paid.beginning_of_month }
    @paid_payments = @all_payments.paid.all
    @paid_payments = @paid_payments.group_by { |p| p.date_paid.beginning_of_month }
    @outstanding_payments = @all_payments.outstanding.all + @all_payments.refunded.all
    @outstanding_payments = @outstanding_payments.group_by { |p| p.due_date.beginning_of_month }

    @monthly_paid = Date::ABBR_MONTHNAMES[1..12].map {|m| [m, 0]}
    @monthly_outstanding = Date::ABBR_MONTHNAMES[1..12].map {|m| [m, 0, 'Amount: 0']}
    
    @year_paid_total = 0
    @paid_payments.sort.map do |month, p|
      index = @monthly_paid.index {|e| e[0] == month.strftime('%b')}
      total = p.map(&:amount).reduce(&:+).to_f
      @monthly_paid[index][1] = total
      @year_paid_total += total
      @monthly_paid[index][2] = "Amount: #{decimal_amount(total)}"
      @monthly_paid[index][3] = p.count
    end

    @year_unpaid_total = 0
    @outstanding_payments.sort.map do |month, p|
      index = @monthly_outstanding.index { |e| e[0] == month.strftime('%b') }
      total = p.map(&:amount).reduce(&:+).to_f
      @year_unpaid_total += total
      @monthly_outstanding[index][1] = total
      @monthly_outstanding[index][2] = "Amount: #{decimal_amount(total)}"
      @monthly_outstanding[index][3] = p.count
    end

    @month_paid = @paid_payments[Date.today.beginning_of_month] || []
    @month_unpaid = @outstanding_payments[Date.today.beginning_of_month] || []

    ### To retrieve Payments awaiting approval ###
    if tenant?
      # @awaiting_payments = current_user.all_contracts.payments.pending
      @awaiting_payments = Payment.pending
                                  .joins(:contract)
                                  .where('contracts.tenant_id = ?', current_user.id)
    end
  end

  private
  def check_subscription
    landlord = current_user
    if tenant?
      return
    end
    if landlord.subscription_expired?
      redirect_to account_summary_path, alert: 'Your subscription has expired today, please renew to use our app.'
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/show.html.haml
.row
  .col-sm-12
    .page-header
      %h1
        Dashboard
        %small overview &amp; stats

.row
  .col-sm-12
    .row.space12
      %ul.mini-stats.col-sm-12
        %li.col-sm-3
          .values
            %strong
              %span.badge.badge-info
                = link_to @properties.count, properties_path
            %span.text-info Total Properties
        %li.col-sm-3
          .values
            %strong
              %span.badge.badge-warning
                = link_to @contracts.count, contracts_path
            %span.text-info Active Contracts
        %li.col-sm-3
          .values
            %strong
              %span.badge.badge-success
                = link_to @monthly_paid[@current_month - 1][3] || 0, payments_paid_path
            %span.text-info # of Payments Collected for the Month
        %li.col-sm-3
          .values
            %strong
              %span.badge.badge-danger
                = link_to @outstanding_payments.count, payments_outstanding_path
            %span.text-info # of Payment Uncollected for the Month

.row
  .col-sm-9
    .panel.panel-default
      .panel-heading
        %i.fa.fa-external-link-square
        Rent Collection Trend
        .panel-tools
          %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
          %a.btn.btn-xs.btn-link.panel-expand{:href => "#"}
            %i.fa.fa-resize-full
          %a.btn.btn-xs.btn-link.panel-close{:href => "#"}
            %i.fa.fa-times
      .panel-body
        %strong Paid Rents
        .flot-small-container
          #paidPlots.flot-placeholder
        %br
        %strong Unpaid Rents
        .flot-small-container
          #unpaidPlots.flot-placeholder
        %br
        %br
        %em
          Note: Computed based on
          %b Date Paid
          , if a rent for March is paid advanced on January, it will be computed as earning on January because it was collected on January
  .col-sm-3
    .panel.panel-default
      .panel-heading
        %i.clip-pie
        Totals
        .panel-tools
          %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
          %a.btn.btn-xs.btn-link.panel-close{:href => "#"}
            %i.fa.fa-times
      .panel-body
        .table-responsive
          %table.table.table-hover
            %thead
              %tr
                %th Month
                %th Paid
                %th Unpaid
            %tbody
              - 12.times do |index|
                %tr
                  %td= @monthly_paid[index][0]
                  %td= @monthly_paid[index][1]
                  %td= @monthly_outstanding[index][1]

        %br
        .text-right
          %h4
            %strong.pull-right GBP #{ decimal_amount(@year_paid_total) }
            %br
            %small Total Paid Rents
            .clearfix
          %h4
            %strong.pull-right GBP #{ decimal_amount(@year_unpaid_total) }
            %br
            %small Total Unpaid Rents

.row
  .col-sm-7
    .panel.panel-default
      .panel-heading
        %i.clip-users-2
        Paid Rents This Month
        .panel-tools
          %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
          %a.btn.btn-xs.btn-link.panel-close{:href => "#"}
            %i.fa.fa-times
      .panel-body.panel-scroll{:style => "height:300px"}
        %table#sample-table-1.table.table-striped.table-hover
          %thead
            %tr
              %th #{inverse_user_type} Name
              %th Due date
              %th Date Paid
              %th Amount
              %th Status
          %tbody
            - for p in @month_paid
              %tr
                - if landlord?
                  %td= p.contract.tenant_info(current_user)[:name]
                - elsif tenant?
                  %td= p.contract.landlord.name
                %td= p.due_date
                %td= p.date_paid
                %td= p.precise_amount
                %td= p.status
        %br
        %br
        .text-right
          %h4
            %strong.pull-right GBP #{ @month_paid.map(&:amount).reduce(&:+) }
            %br
            %small Total Paid Rents for #{ Date.today.strftime("%b %Y") }
            .clearfix
  .col-sm-5
    .panel.panel-default
      .panel-heading
        %i.clip-users-2
        Unpaid Rents This Month
        .panel-tools
          %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
          %a.btn.btn-xs.btn-link.panel-close{:href => "#"}
            %i.fa.fa-times
      .panel-body.panel-scroll{:style => "height:300px"}
        %table#sample-table-1.table.table-striped.table-hover
          %thead
            %tr
              %th #{inverse_user_type} Name
              %th Due date
              %th Amount
              %th Status
          %tbody
            - for p in @month_unpaid
              %tr
                - if landlord?
                  %td= p.contract.tenant_info(current_user)[:name]
                - elsif tenant?
                  %td= p.contract.landlord.name
                %td= p.due_date
                %td= p.precise_amount
                %td= p.status
        %br
          %br
          .text-right
            %h4
              %strong.pull-right GBP #{ @month_unpaid.map(&:amount).reduce(&:+) || 0 }
              %br
              %small Total Unpaid Rents for #{ Date.today.strftime("%b %Y") }
              .clearfix

.row
  .col-sm-6
    .panel.panel-default
      - if landlord?
        .panel-heading
          %i.clip-users-2
          New contracts starting this month
          .panel-tools
            %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
            %a.btn.btn-xs.btn-link.panel-close{:href => "#"}
              %i.fa.fa-times
        .panel-body.panel-scroll{:style => "height:300px"}
          %table#sample-table-1.table.table-striped.table-hover
            %thead
              %tr
                %th #{inverse_user_type} Name
                %th Property / Room #
                %th Rent
            %tbody
              - for c in @contracts.started_this_month
                %tr
                  %td= c.tenant_info(current_user)[:name]
                  %td= "#{c.property.name} / #{c.room_number}"
                  %td= c.rental_amount
      - elsif tenant?
        .panel-heading
          %i.clip-users-2
          Payments awaiting approval
          .panel-tools
            %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
            %a.btn.btn-xs.btn-link.panel-close{:href => "#"}
              %i.fa.fa-times
        .panel-body.panel-scroll{:style => "height:300px"}
          %table#sample-table-1.table.table-striped.table-hover
            %thead
              %tr
                %th Property / Room #
                %th Amount
                %th Date Paid
            %tbody
              - for c in @awaiting_payments
                %tr
                  %td= "#{c.property.name} / #{c.contract.room_number}"
                  %td= c.precise_amount
                  %td= c.date_paid
  .col-sm-6
    .panel.panel-default
      .panel-heading
        %i.clip-users-2
        Contracts ending this month
        .panel-tools
          %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
          %a.btn.btn-xs.btn-link.panel-close{:href => "#"}
            %i.fa.fa-times
      .panel-body.panel-scroll{:style => "height:300px"}
        %table#sample-table-1.table.table-striped.table-hover
          %thead
            %tr
              %th #{inverse_user_type} Name
              %th Property / Room #
              %th Rent
          %tbody
            - for c in @contracts.finished_this_month
              %tr
                - if landlord?
                  %td= c.tenant_info(current_user)[:name]
                - elsif tenant?
                  %td= c.landlord.name
                %td= "#{c.property.name} / #{c.room_number}"
                %td= c.rental_amount

:javascript
  var Dashboard = function () {
    var runRentCollection = function() {
      var data_category = #{@monthly_paid};
      $.plot("#paidPlots", [data_category], {
        series: {
          bars: {
            show: true,
            barWidth: 0.6,
            align: "center",
            fillColor: "#4DBEF4",
            lineWidth: 0
          }
        },
        xaxis: {
          mode: "categories",
          tickLength: 0
        },
        grid: { hoverable: true, clickable: true }
      });

      var data_category = #{@monthly_outstanding};
      $.plot("#unpaidPlots", [data_category], {
        series: {
          bars: {
            show: true,
            barWidth: 0.6,
            align: "center",
            fillColor: "#4DBEF4",
            lineWidth: 0
          }
        },
        xaxis: {
          mode: "categories",
          tickLength: 0
        },
        grid: { hoverable: true, clickable: true }
      });
    };
    return {
      init: function () {
        runRentCollection();
      }
    };
  }();

  $(document).ready(function() {
    Dashboard.init();

    var changeTooltipPosition = function(event) {
      var tooltipX = event.pageX - 8;
      var tooltipY = event.pageY + 8;
      $('div.tooltip').css({top: tooltipY, left: tooltipX});
    };

    var showTooltip = function(event) {
      $('div.tooltip').remove();
      $('<div class="tooltip">I\' am tooltips! tooltips! tooltips! :)</div>')
            .appendTo('body');
      changeTooltipPosition(event);
    };

    $("#paidPlots, #unpaidPlots").bind("plotclick", function (event, pos, item) {
      $("#tooltip").remove();
      if (item) {
        var tooltip = item.series.data[item.dataIndex][2];

        $('<div id="tooltip">' + tooltip + '</div>')
          .css({
            position: 'absolute',
            display: 'none',
            top: item.pageY + 5,
            left: item.pageX + 5,
            border: '1px solid #fdd',
            padding: '2px',
            'background-color': '#fee',
            opacity: 0.80 })
          .appendTo("body").fadeIn(200);


        showTooltip(item.pageX, item.pageY, tooltip);
      }
    });
  });