config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'payments/outstanding'

  get 'payments/paid'

  root to: 'visitors#home'

  devise_for :users, controllers: { registrations: 'registrations'}

  # landing pages
  get '/about', to: 'visitors#about', as: 'about'
  get '/features', to: 'visitors#features', as: 'features'
  get '/rightmove', to: 'visitors#rightmove', as: 'rightmove'
  get '/vacancies', to: 'visitors#vacancies', as: 'vacancies'
  get '/policy', to: 'visitors#policy', as: 'policy'
  get '/videos', to: 'visitors#videos', as: 'videos'
  get '/pricing', to: 'visitors#pricing', as: 'pricing'
  get '/testimonials', to: 'visitors#testimonials', as: 'testimonials'
  get '/contactus', to: 'visitors#contactus', as: 'contactus'
  post '/contactus', to: 'visitors#send_contactus', as: 'send_contactus'
  get '/instruction', to: 'visitors#instruction', as: 'instruction'

  # dashboard page
  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  # user account pages
  get '/profile', to: 'users#edit', as: 'profile'
  get '/account_summary', to: 'users#show', as: 'account_summary'
  post '/profile', to: 'users#update', as: 'update_profile'

  # properties
  resources :properties

  # connections
  get '/connections/new', to: 'connections#new', as: 'add_connection'
  post '/connections', to: 'connections#create', as: 'create_connection'
  get '/connections', to: 'connections#index', as: 'connections'
  get '/connections/approve/:id', to: 'connections#approve', as: 'approve_connection'
  delete '/connections/:id', to: 'connections#decline', as: 'decline_connection'

  # contracts
  resources :contracts
  get '/active_contracts', to: 'contracts#active_contracts', as: 'active_contracts'
  get '/finished_contracts', to: 'contracts#finished_contracts', as: 'finished_contracts'

  # payments
  get '/payments/outstanding', to: 'payments#outstanding', as: 'outstanding_payments'
  get '/payments/paid', to: 'payments#paid', as: 'paid_payments'
  delete '/payments/:id', to: 'payments#destroy', as: 'payment'
  get '/payments/:return_token/confirm', to: 'payments#confirm', as: 'payment_confirm'
  get '/payments/:id/accept', to: 'payments#accept', as: 'payment_accept'
  get '/payments/:id/refund', to: 'payments#refund', as: 'payment_refund'

  # private payments
  resources :private_payments

  # charges
  resources :charges
  post '/charge_succeed' => 'charges#succeed'

  namespace :api, defaults: {format: :json} do
    resource :auth, controller: :auth, only: [] do
      get :login, on: :collection
    end
    resource :dashboard, controller: :dashboard, only: [] do
      get :counts, on: :collection
    end
    resources :properties, only: [:index]
  end

end

app/models/contract.rb
class Contract < ActiveRecord::Base

  belongs_to :landlord, class_name: 'User', foreign_key: :landlord_id
  belongs_to :tenant, class_name: 'User', foreign_key: :tenant_id
  belongs_to :property
  belongs_to :connection
  has_many :payments, dependent: :destroy

  validates_presence_of :property_id, :start_date, :end_date, :room_number, :rental, :pay_date
  validates_presence_of :connection, :property

  default_scope -> { where('finished_at is null') }

  scope :finished, -> { unscoped.where('finished_at is not null') }
  scope :started_this_month, -> { unscoped.where('created_at >= ? && created_at < ?', Date.today.beginning_of_month, Date.today.beginning_of_month + 1.month) }
  scope :finished_this_month, -> { finished.where('finished_at >= ? && finished_at < ?', Date.today.beginning_of_month, Date.today.beginning_of_month + 1.month) }

  def period
    "#{self.start_date.strftime("%Y-%m-%d")} ~ #{self.end_date.strftime("%Y-%m-%d")}"
  end

  def tenant_info current_user
    connection.nil? ? {} : self.connection.connected_user_info(current_user)
  end

  def rental_amount
    '%.2f' % rental
  end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @active_contracts = current_user.active_contracts
    @finished_contracts = current_user.all_contracts.finished
  end

  def active_contracts
    @active_contracts = current_user.active_contracts
  end

  def finished_contracts
    @finished_contracts = current_user.finished_contracts
    # @finished_contracts = Contract.where('tenant_id = ? OR landlord_id = ?', current_user.id, current_user.id)
  end

  def new
    if current_user.properties.blank?
      redirect_to new_property_path, notice: 'You have to create more than 1 property to start a contract.' and return
    end
    @contract = Contract.new
  end

  def create
    if !current_user.is_active
      redirect_to contracts_path, :alert => "You have to subscribe to manage the contracts." and return
    elsif current_user.contract_max_count != -1 && current_user.contract_count >= current_user.contract_max_count
      redirect_to contracts_path, :alert => "You could have #{current_user.contract_max_count} contracts with your plan, if you want to add more contracts, please upgrade plan." and return
    end

    @contract = Contract.new permit_contract_params
    @contract.landlord_id = current_user.id

    if @contract.save
      generate_payments @contract
      current_user.contract_count = current_user.contract_count + 1
      current_user.save

      redirect_to contracts_path, notice: 'Contract is successfully created.'
    else
      render :new
    end
  end

  def edit
    @contract = Contract.find params[:id]
  end

  def show
    @contract = Contract.includes(:payments).includes(:property)
                        .includes(:landlord).includes(:tenant)
                        .find(params[:id])
    @paid_payments = @contract.payments.paid
    @outstanding_payments = @contract.payments.outstanding
    @tenant_info = @contract.tenant_info current_user
  end

  def update
    @contract = Contract.find params[:id]

    if @contract.update_attributes permit_contract_params
      update_payments @contract

      redirect_to contracts_path, notice: 'Contract is successfully started.'
    else
      render :edit
    end
  end

  def destroy
    @contract = Contract.find params[:id]
    @contract.finished_at = Time.now

    if @contract.save
      redirect_to new_contract_path, notice: 'Contract is successfully finished.'
    else
      redirect_to contracts_path, alert: 'Failed to finish contract.'
    end
  end

  private

  def generate_payments contract
    num_of_months = (contract.end_date.year * 12 + contract.end_date.month) - (contract.start_date.year * 12 + contract.start_date.month)

    num_of_months.times do |n|
      calc_date = contract.start_date + (n + 1).months
      days = Time.days_in_month(calc_date.month, calc_date.year)
      if contract.pay_date > days
        calc_date = calc_date.change(day: days)
      else
        calc_date = calc_date.change(day: contract.pay_date)
      end

      payment = Payment.new
      payment.landlord = contract.landlord
      payment.amount = contract.rental
      payment.property = contract.property
      payment.contract = contract
      payment.status = Payment::STATUS_UNPAID
      payment.paid_type = nil
      payment.due_date = calc_date
      payment.date_paid = nil
      payment.return_token = SecureRandom.urlsafe_base64(16)

      payment.save
    end
  end

  def update_payments contract
    updated_ids = []

    current_payments = Payment.where(contract_id: contract.id)
    current_ids = current_payments.map(&:id)

    num_of_months = (contract.end_date.year * 12 + contract.end_date.month) - (contract.start_date.year * 12 + contract.start_date.month)

    num_of_months.times do |n|

      calc_date = contract.start_date + (n + 1).months

      days = Time.days_in_month(calc_date.month, calc_date.year)
      if contract.pay_date > days
        calc_date = calc_date.change(day: days)
      else
        calc_date = calc_date.change(day: contract.pay_date)
      end

      exist_payment = false
      current_payments.each do |cp|
        if cp.due_date.strftime("%Y%m") == calc_date.strftime("%Y%m")
          if cp.status == Payment::STATUS_UNPAID
            cp.due_date = calc_date
            cp.save
          end
          updated_ids.push cp.id
          exist_payment = true
        end
      end

      unless exist_payment
        payment = Payment.new
        payment.landlord = contract.landlord
        payment.amount = contract.rental
        payment.property = contract.property
        payment.contract = contract
        payment.status = Payment::STATUS_UNPAID
        payment.paid_type = nil
        payment.due_date = calc_date
        payment.date_paid = nil
        payment.return_token = SecureRandom.urlsafe_base64(16)

        payment.save
      end
    end

    Payment.destroy(current_ids - updated_ids)
  end

  def permit_contract_params
    params.require(:contract).permit(:tenant_id, :property_id, :room_number, :start_date, :end_date,
                                     :rental, :pay_date, :notes, :connection_id)
  end

end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.haml
= form_for @contract do |f|
  = render partial: 'shared/form_errors', locals: {model: f.object}
  .panel.panel-default
    .panel-heading
      %i.fa.fa-external-link-square
      ADD CONTRACT
      .panel-tools
        %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
        %a.btn.btn-xs.btn-link.panel-close{:href => "#"}
          %i.fa.fa-times
    .panel-body
      .row
        .col-sm-6
          .form-group
            = f.label :tenant_id, 'Tenant', class: 'control-label'
            = f.select :tenant_id, current_user.approved_connections.collect {|c| [c.connected_user_info(current_user)[:name], c.connected_user_info(current_user)[:id], {'data-connection_id' => c.id}]}, {}, class: 'form-control', id: 'contract-tenant-select'
            = f.hidden_field :connection_id, id: 'contract-connection-id'
          .form-group
            = f.label :property_id, 'Property', class: 'control-label'
            = f.select :property_id, current_user.properties.collect {|c| [c.name, c.id]}, {}, class: 'form-control'
          .form-group
            = f.label :start_date, 'Start Date', class: 'control-label'
            .input-group
              = f.text_field :start_date, class: 'form-control date-picker', id: 'contract-start-date'
              %span.input-group-addon
                %i.fa.fa-calendar
          .form-group
            = f.label :end_date, 'End Date', class: 'control-label'
            .input-group
              = f.text_field :end_date, class: 'form-control date-picker', id: 'contract-end-date'
              %span.input-group-addon
                %i.fa.fa-calendar
        .col-sm-6
          .form-group
            = f.label :room_number, 'Room Number', class: 'control-label'
            = f.number_field :room_number, :placeholder => "Room Number", class: 'form-control'
          .form-group
            = f.label :rental, 'Rental Amount', class: 'control-label'
            = f.text_field :rental, :placeholder => "Rental Amount", class: 'form-control'
          .form-group
            = f.label :pay_date, 'Pay Date', class: 'control-label'
            = f.select :pay_date, (1..31), {},  class: 'form-control'
          .form-group
            = f.label :notes, 'Notes', class: 'control-label'
            = f.text_area :notes, :placeholder => "Notes", rows: 6, class: 'form-control'

      .pull-right
        - if @contract.new_record?
          = f.submit 'Add Contract', class: 'btn btn-primary'
        - else
          = f.submit 'Update Contract', class: 'btn btn-primary'

app/views/contracts/active_contracts.html.haml
.row
  .col-sm-12
    .page-header
      %h1
        Active Contracts
        %small Manage Contracts

.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %i.fa.fa-external-link-square
        Active Contracts
        .panel-tools
          %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
          %a.btn.btn-xs.btn-link.panel-refresh{:href => "#"}
            %i.fa.fa-refresh
      .panel-body
        %table#active-contracts-table.table.table-striped.table-bordered.table-hover.table-full-width
          %thead
            %tr
              %th Property Name
              %th Room Number
              %th Rental Amount
              %th Landlord Name
              %th Contact Period
              %th Pay Date
              -#%th Actions
          %tbody
            - @active_contracts.each do |p|
              %tr
                %td= p.property.name
                %td= p.room_number
                %td= p.rental_amount
                %td= p.landlord.name
                %td= p.period
                %td= p.pay_date
                -#%td
                -#  = link_to edit_contract_path(p), class: 'btn btn-purple' do
                -#    %i.fa.fa-pencil
                -#  = link_to contract_path(p), class: 'btn btn-blue' do
                -#    %i.fa.fa-arrow-circle-right
                -#  = link_to contract_path(p), class: 'btn btn-green', method: :delete, 'data-confirm' => 'Are you sure?' do
                -#    %i.fa.fa-dot-circle-o

app/views/contracts/edit.html.haml
.row
  .col-sm-12
    .page-header
      %h1
        Edit Contract
        %small Contract Details and Summary

.row
  .col-sm-12
    = render 'shared/messages'
    = render 'form'

app/views/contracts/finished_contracts.html.haml
.row
  .col-sm-12
    .page-header
      %h1
        Inactive Contracts
        %small Manage Contracts

.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %i.fa.fa-external-link-square
        Finished Contracts
        .panel-tools
          %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
          %a.btn.btn-xs.btn-link.panel-refresh{:href => "#"}
            %i.fa.fa-refresh
      .panel-body
        %table#finished-contracts-table.table.table-striped.table-bordered.table-hover.table-full-width
          %thead
            %tr
              %th Property Name
              %th Room Number
              %th Rental Amount
              %th Landlord Name
              %th Contact Period
              %th Finished At
          %tbody
            - @finished_contracts.each do |p|
              %tr
                %td= p.property.name
                %td= p.room_number
                %td= p.rental_amount
                %td= p.landlord.name
                %td= p.period
                %td= p.finished_at

app/views/contracts/index.html.haml
.row
  .col-sm-12
    .page-header
      %h1
        List of Contracts
        %small Manage Contracts
.row
  .col-sm-12
    = render 'shared/messages'
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %i.fa.fa-external-link-square
        Active Contracts
        .panel-tools
          %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
          %a.btn.btn-xs.btn-link.panel-refresh{:href => "#"}
            %i.fa.fa-refresh
      .panel-body
        %table#active-contracts-table.table.table-striped.table-bordered.table-hover.table-full-width
          %thead
            %tr
              %th Property Name
              %th Room Number
              %th Rental Amount
              %th Tenant Name
              %th Contact Period
              %th Pay Date
              %th Actions
          %tbody
            - @active_contracts.each do |p|
              %tr
                %td= p.property.name
                %td= p.room_number
                %td= p.rental_amount
                %td= p.tenant_info(current_user)[:name]
                %td= p.period
                %td= p.pay_date
                %td
                  - if p.paused
                    %span You contract is paused.
                    %br
                    %span Please
                    = link_to 'upgrade', account_summary_path
                    %span subscription plan.
                  - else
                    = link_to edit_contract_path(p), class: 'btn btn-purple' do
                      %i.fa.fa-pencil
                    = link_to contract_path(p), class: 'btn btn-blue' do
                      %i.fa.fa-eye
                    = link_to contract_path(p), class: 'btn btn-danger', method: :delete, 'data-confirm' => 'Are you sure?' do
                      %i.fa.fa-times.fa-white
    .panel.panel-default
      .panel-heading
        %i.fa.fa-external-link-square
        Finished Contracts
        .panel-tools
          %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
          %a.btn.btn-xs.btn-link.panel-refresh{:href => "#"}
            %i.fa.fa-refresh
      .panel-body
        %table#finished-contracts-table.table.table-striped.table-bordered.table-hover.table-full-width
          %thead
            %tr
              %th Property Name
              %th Room Number
              %th Rental Amount
              %th Tenant Name
              %th Contact Period
              %th Finished At
          %tbody
            - @finished_contracts.each do |p|
              %tr
                %td= p.property.name
                %td= p.room_number
                %td= p.rental_amount
                %td= p.tenant_info(current_user)[:name]
                %td= p.period
                %td= p.finished_at

app/views/contracts/new.html.haml
.row
  .col-sm-12
    .page-header
      %h1
        New Contract
        %small Add / Manage Contracts

.row
  .col-sm-12
    = render 'shared/messages'
    = render 'form'

app/views/contracts/show.html.haml
.row
  .col-sm-12
    .page-header
      %h1
        View Contract
        %small Contract Details and Summary

.row
  .col-sm-12
    .tab-content
      .row
        .col-sm-4
          .user-left
            %table.table.table-condensed.table-hover
              %thead
                %tr
                  %th{:colspan => "3"} Contract Information
              %tbody
                %tr
                  %td property name:
                  %td
                    = @contract.property.name
                  %td
                    = link_to edit_property_path(@contract.property) do
                      %i.fa.fa-pencil.edit-user-info
                %tr
                  %td room number:
                  %td= @contract.room_number
                  %td
                    = link_to edit_contract_path(@contract) do
                      %i.fa.fa-pencil.edit-user-info
                %tr
                  %td contract start date:
                  %td= @contract.start_date
                  %td
                    = link_to edit_contract_path(@contract) do
                      %i.fa.fa-pencil.edit-user-info
                %tr
                  %td contract end date:
                  %td= @contract.end_date
                  %td
                    = link_to edit_contract_path(@contract) do
                      %i.fa.fa-pencil.edit-user-info
                %tr
                  %td rental amount:
                  %td= @contract.rental
                  %td
                    = link_to edit_contract_path(@contract) do
                      %i.fa.fa-pencil.edit-user-info
                %tr
                  %td pay date:
                  %td= @contract.pay_date
                  %td
                    = link_to edit_contract_path(@contract) do
                      %i.fa.fa-pencil.edit-user-info
            .pull-right
              = link_to edit_contract_path(@contract), class: 'btn btn-info btn-squared btn-lg' do
                Edit Contract
                %i.fa.fa-eye
        .col-sm-4
          %table.table.table-condensed.table-hover
            %thead
              %tr
                %th{:colspan => "2"} Landlord Information
            %tbody
              %tr
                %td{:colspan => "2"}
                  .center
                    %h4= @contract.landlord.name
                    .user-image
                      .fileupload-new.thumbnail
                        = image_tag @contract.landlord.avatar.url(:medium)
              %tr
                %td address:
                %td= @contract.landlord.address
              %tr
                %td phone:
                %td= @contract.landlord.phone
              %tr
                %td company name:
                %td= @contract.landlord.company_name.presence || 'N/A'
              %tr
                %td company description:
                %td= @contract.landlord.company_desc.presence || 'N/A'
              %tr
                %td vat number:
                %td= @contract.landlord.vat_number.presence || 'N/A'
        .col-sm-4
          %table.table.table-condensed.table-hover
            %thead
              %tr
                %th{:colspan => "2"} Tenant Information
            %tbody
              - if @contract.tenant.nil?
                %tr
                  %td name:
                  %td= @tenant_info[:name]
              - else
                %tr
                  %td{:colspan => "2"}
                    .center
                      %h4= @tenant_info[:name]
                      .user-image
                        .fileupload-new.thumbnail
                          = image_tag @contract.tenant.avatar.url(:medium)
                %tr
                  %td gender:
                  %td= @contract.tenant.gender
              %tr
                %td email:
                %td= @tenant_info[:email]
              %tr
                %td phone:
                %td= @tenant_info[:phone] || 'N/A'
              %tr
                %td notes:
                %td= @tenant_info[:notes] || 'N/A'