config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'payments/outstanding'

  get 'payments/paid'

  root to: 'visitors#home'

  devise_for :users, controllers: { registrations: 'registrations'}

  # landing pages
  get '/about', to: 'visitors#about', as: 'about'
  get '/features', to: 'visitors#features', as: 'features'
  get '/rightmove', to: 'visitors#rightmove', as: 'rightmove'
  get '/vacancies', to: 'visitors#vacancies', as: 'vacancies'
  get '/policy', to: 'visitors#policy', as: 'policy'
  get '/videos', to: 'visitors#videos', as: 'videos'
  get '/pricing', to: 'visitors#pricing', as: 'pricing'
  get '/testimonials', to: 'visitors#testimonials', as: 'testimonials'
  get '/contactus', to: 'visitors#contactus', as: 'contactus'
  post '/contactus', to: 'visitors#send_contactus', as: 'send_contactus'
  get '/instruction', to: 'visitors#instruction', as: 'instruction'

  # dashboard page
  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  # user account pages
  get '/profile', to: 'users#edit', as: 'profile'
  get '/account_summary', to: 'users#show', as: 'account_summary'
  post '/profile', to: 'users#update', as: 'update_profile'

  # properties
  resources :properties

  # connections
  get '/connections/new', to: 'connections#new', as: 'add_connection'
  post '/connections', to: 'connections#create', as: 'create_connection'
  get '/connections', to: 'connections#index', as: 'connections'
  get '/connections/approve/:id', to: 'connections#approve', as: 'approve_connection'
  delete '/connections/:id', to: 'connections#decline', as: 'decline_connection'

  # contracts
  resources :contracts
  get '/active_contracts', to: 'contracts#active_contracts', as: 'active_contracts'
  get '/finished_contracts', to: 'contracts#finished_contracts', as: 'finished_contracts'

  # payments
  get '/payments/outstanding', to: 'payments#outstanding', as: 'outstanding_payments'
  get '/payments/paid', to: 'payments#paid', as: 'paid_payments'
  delete '/payments/:id', to: 'payments#destroy', as: 'payment'
  get '/payments/:return_token/confirm', to: 'payments#confirm', as: 'payment_confirm'
  get '/payments/:id/accept', to: 'payments#accept', as: 'payment_accept'
  get '/payments/:id/refund', to: 'payments#refund', as: 'payment_refund'

  # private payments
  resources :private_payments

  # charges
  resources :charges
  post '/charge_succeed' => 'charges#succeed'

  namespace :api, defaults: {format: :json} do
    resource :auth, controller: :auth, only: [] do
      get :login, on: :collection
    end
    resource :dashboard, controller: :dashboard, only: [] do
      get :counts, on: :collection
    end
    resources :properties, only: [:index]
  end

end

app/views/shared/_app_header.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.clip-list-2
      = link_to dashboard_path, class: 'navbar-brand' do
        = image_tag 'logo-backend.png'
    .navbar-tools
      %ul.nav.navbar-right
        %li.dropdown.current-user
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            = image_tag current_user.avatar.url(:thumb), class: 'circle-img'
            %span.username #{current_user.name} #{current_user.subscription_type if landlord?}
            %i.clip-chevron-down
          %ul.dropdown-menu
            - if landlord?
              %li
                = link_to account_summary_path do
                  %i.clip-calendar
                  \&nbsp;Account Summary
            %li
              = link_to profile_path do
                %i.clip-user-2
                \&nbsp;Edit Profile
            %li.divider
            %li
              = link_to destroy_user_session_path, method: :delete do
                %i.clip-exit
                \&nbsp;Log Out

app/views/shared/_app_page_header.html.haml
.row
  .col-sm-12
    %ol.breadcrumb
      %li
        %i.clip-home-3
        %a{:href => "#"}
          Home
      %li.active
        Dashboard
      %li.search-box
        %form.sidebar-search
          .form-group
            %input{:placeholder => "Start Searching...", :type => "text"}
              %button.submit
                %i.clip-search-3

app/views/shared/_app_sidebar.html.haml
.main-navigation.navbar-collapse.collapse
  .navigation-toggler
    %i.clip-chevron-left
    %i.clip-chevron-right
  %ul.main-navigation-menu
    %li{class: "#{selected_menu('dashboard', '')}"}
      = link_to dashboard_path do
        %i.clip-screen
        %span.title Dashboard
        %span.selected
    %li{class: "#{selected_menu('properties', '')}"}
      %a{:href => "javascript:void(0)"}
        %i.clip-home-3
        %span.title Properties
        %i.icon-arrow
        %span.selected
      %ul.sub-menu
        - if landlord?
          %li{class: "#{selected_menu('properties', 'new')}"}
            = link_to new_property_path do
              %span.title Add New Property
        %li{class: "#{selected_menu('properties', 'index')}"}
          = link_to properties_path do
            %span.title List of Properties
    %li{class: "#{selected_menu('connections', '')}"}
      %a{:href => "javascript:void(0)"}
        %i.clip-user-2
        %small inverse user type #{inverse_user_type}
        %span.title #{inverse_user_type.pluralize}
        %i.icon-arrow
        %span.selected
      %ul.sub-menu
        %li{class: "#{selected_menu('connections', 'new')}"}
          = link_to add_connection_path do
            %span.title Add #{inverse_user_type}
        %li{class: "#{selected_menu('connections', 'index')}"}
          = link_to connections_path do
            %span.title List of #{inverse_user_type.pluralize}
    %li{class: "#{selected_menu('contracts', '')}"}
      %a{:href => "javascript:void(0)"}
        %i.clip-pencil
        %span.title Contracts
        %i.icon-arrow
        %span.selected
      %ul.sub-menu
        - if landlord?
          %li{class: "#{selected_menu('contracts', 'new')}"}
            = link_to new_contract_path do
              %span.title Add New Contract
          %li{class: "#{selected_menu('contracts', 'index')}"}
            = link_to contracts_path do
              %span.title List of Contracts
        - elsif tenant?
          %li{class: "#{selected_menu('contracts', 'active_contracts')}"}
            = link_to active_contracts_path do
              %span.title Active Contracts
          %li{class: "#{selected_menu('contracts', 'finished_contracts')}"}
            = link_to finished_contracts_path do
              %span.title Finished/Inactive Contracts
    %li{class: "#{selected_menu('payments', '')}"}
      %a{:href => "javascript:void(0)"}
        %i.clip-grid-6
        %span.title Payments
        %i.icon-arrow
        %span.selected
      %ul.sub-menu
        %li{class: "#{selected_menu('payments', 'outstanding')}"}
          = link_to outstanding_payments_path do
            %span.title Outstanding Payments
        %li{class: "#{selected_menu('payments', 'paid')}"}
          = link_to paid_payments_path do
            %span.title Paid Payments
    / - if tenant?
    /   %li{class: "#{selected_menu('private_payments', '')}"}
    /     = link_to private_payments_path do
    /       %i.clip-grid-2
    /       %span.title Private Payments
    /       %span.selected
    %li{class: "#{selected_menu('users', '')}"}
      %a{:href => "javascript:void(0)"}
        %i.clip-cog-2
        %span.title Profile Settings
        %i.icon-arrow
        %span.selected
      %ul.sub-menu
        - if landlord?
          %li
            = link_to account_summary_path do
              %span.title Subscription
        %li
          = link_to profile_path do
            %span.title Edit Profile

app/views/shared/_form_errors.html.haml
- count = model.errors.count unless model.nil?
- if count > 0
  .alert.alert-block.alert-danger.fade.in
    %button.close{'data-dismiss' => 'alert'}
      &times;
    %h4.alert-heading
      %i.fa.fa-times-circle Error!
    - model.errors.full_messages.each do |message|
      %p #{message}

app/views/shared/_landing_footer.html.haml
%footer.footer-wrapper
  .container
    .col-lg-4.col-md-4.col-sm-8
      .widget
        %h2.general-title
          %span Twitter Stream
        .tweets
          %ul
            %li
              %span.content
                Property News: Tenants face eviction as landlords capitalise on rising hourse prices
                %br
                %a(href="http://www.geniebytes.com" target="_blank") http://ow.ly/2K7dxF

        %a.twitter-follow-button{"data-show-count" => "false", :href => "https://twitter.com/GenieLetsApp"} 
          | Follow @genielets
          :javascript
            !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
    .col-lg-4.col-md-4.col-sm-8
      .widget
        %h2.general-title
          %span Social Links
        .tweets
          %ul.dm-social{:style => "float:none; text-align: center;"}
            %li
              %a.icon-facebook{"data-placement" => "bottom", "data-toggle" => "tooltip", :href => "https://www.facebook.com/Genie.Lets", :title => "Facebook", target: '_blank'} Facebook
            %li
              %a.icon-google-plus{"data-placement" => "bottom", "data-toggle" => "tooltip", :href => "https://plus.google.com/101713448702200686241", :title => "Google+", target: '_blank'} Google+
            %li
              %a.icon-twitter{"data-placement" => "bottom", "data-toggle" => "tooltip", :href => "https://twitter.com/GenieLetsApp", :title => "Twitter", target: '_blank'} Twitter
            %li
              %a.icon-pinterest{"data-toggle" => "tooltip", "data-placement" => "bottom", :href => "http://www.pinterest.com/alan1915",  :title => "Pinterest", target: '_blank'} Pinterest
            %li
              %a.icon-linkedin{"data-toggle" => "tooltip", "data-placement" => "bottom", :href => "https://www.linkedin.com/profile/view?id=356181760",  :title => "Linked", target: '_blank'} LinkedIn
    .col-lg-4.col-md-4.col-sm-8
      .widget
        %h2.general-title
          %span Contact Details
        %p If you want to talk to us, please use the contact points below.
        %ul.contact-details
          %li
            %i.icon-envelope-alt
            <a href="mailto:info@genielets.com">info@genielets.com</a>
.copyright-wrapper
  .container
    .col-lg-3.col-md-3.col-sm-3
      %span.copyright
        © Copyright 2015 -
        Genielets
    .col-lg-9.col-md-9.col-sm-9
      %nav
        %ul.footer-menu
          %li
            = link_to 'Home', root_path
          %li
            = link_to 'About', about_path
          %li
            = link_to 'Features', features_path
          %li
            = link_to 'Rightmove', rightmove_path
          %li
            = link_to 'Vacancies', vacancies_path
          %li
            = link_to 'Videos', videos_path
          %li
            = link_to 'Pricing', pricing_path
          %li
            = link_to 'Testimonials', testimonials_path
          %li
            = link_to 'Privacy Policy', policy_path
          %li
            = link_to 'Contact Us', contactus_path

app/views/shared/_landing_header.html.haml
.col-lg-2.col-md-2.col-sm-2
  = link_to root_path, class: 'cssLogo' do
    = image_tag 'GenieLets-rightmove-Top-Home-find-a-property-property-news-flatshare-students-property-to-rent-commercial-property-letting-agents-estate-agents.png'
.col-lg-10.col-md-10.col-sm-12
  %nav
    %ul#jetmenu.jetmenu
      %li{class: "#{visitor_status_class('home')}"}
        = link_to 'Home', root_path
      %li{class: "#{visitor_status_class('app')}"}
        %a{href: "#"} App
        %ul.dropdown
          %li
            = link_to 'Features', features_path
          %li
            = link_to 'Pricing', pricing_path
          %li
            = link_to 'Instructions', instruction_path
          %li
            = link_to 'Register', new_user_registration_path(type: User::LANDLORD)
      %li{class: "#{visitor_status_class('about')}"}
        %a{href: "#"} About
        %ul.dropdown
          %li
            = link_to 'About Us', about_path
          %li
            = link_to 'Rightmove', rightmove_path
          %li
            = link_to 'Testimonials', testimonials_path
      %li{class: "#{visitor_status_class('vacancies')}"}
        = link_to 'Vacancies', vacancies_path
      %li{class: "#{visitor_status_class('videos')}"}
        = link_to 'Videos', videos_path
      %li{class: "#{visitor_status_class('contactus')}"}
        = link_to 'Contact Us', contactus_path

app/views/shared/_landing_topbar.html.haml
.row
  .col-lg-6.col-md-6.col-sm-6
    %p.tagline
      Email us : <a href="mailto:CS@genielets.com">info@genielets.com</a>
  .col-lg-6.col-md-6.col-sm-6
    .pull-right
      %ul.top-menu#top-menu
        - if user_signed_in?
          %li
            = link_to dashboard_path do
              %i.icon-user
              My Account
            or
            = link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          %li
            Sign up
            = link_to 'as a Landlord', new_user_registration_path(type: User::LANDLORD)
            or
            = link_to 'as a Tenant', new_user_registration_path(type: User::TENANT)
            , Have an account already?
            = link_to 'Login Here', new_user_session_path

app/views/shared/_messages.html.haml
- if flash.count  > 0
  - class_name = flash.to_hash.keys[0]
  - class_name = 'success' if class_name == 'notice'
  - class_name = 'danger' if class_name == 'alert'
  %div{class: "errorHandler alert alert-#{class_name}"}
    %button.close{'data-dismiss' => 'alert'}
      &times;
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        = content_tag :div, msg

app/views/shared/_navigation.html.haml
%ul.nav
  %li= link_to 'Home', root_path
  = render 'shared/navigation_links'

app/views/shared/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>