config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'payments/outstanding'

  get 'payments/paid'

  root to: 'visitors#home'

  devise_for :users, controllers: { registrations: 'registrations'}

  # landing pages
  get '/about', to: 'visitors#about', as: 'about'
  get '/features', to: 'visitors#features', as: 'features'
  get '/rightmove', to: 'visitors#rightmove', as: 'rightmove'
  get '/vacancies', to: 'visitors#vacancies', as: 'vacancies'
  get '/policy', to: 'visitors#policy', as: 'policy'
  get '/videos', to: 'visitors#videos', as: 'videos'
  get '/pricing', to: 'visitors#pricing', as: 'pricing'
  get '/testimonials', to: 'visitors#testimonials', as: 'testimonials'
  get '/contactus', to: 'visitors#contactus', as: 'contactus'
  post '/contactus', to: 'visitors#send_contactus', as: 'send_contactus'
  get '/instruction', to: 'visitors#instruction', as: 'instruction'

  # dashboard page
  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  # user account pages
  get '/profile', to: 'users#edit', as: 'profile'
  get '/account_summary', to: 'users#show', as: 'account_summary'
  post '/profile', to: 'users#update', as: 'update_profile'

  # properties
  resources :properties

  # connections
  get '/connections/new', to: 'connections#new', as: 'add_connection'
  post '/connections', to: 'connections#create', as: 'create_connection'
  get '/connections', to: 'connections#index', as: 'connections'
  get '/connections/approve/:id', to: 'connections#approve', as: 'approve_connection'
  delete '/connections/:id', to: 'connections#decline', as: 'decline_connection'

  # contracts
  resources :contracts
  get '/active_contracts', to: 'contracts#active_contracts', as: 'active_contracts'
  get '/finished_contracts', to: 'contracts#finished_contracts', as: 'finished_contracts'

  # payments
  get '/payments/outstanding', to: 'payments#outstanding', as: 'outstanding_payments'
  get '/payments/paid', to: 'payments#paid', as: 'paid_payments'
  delete '/payments/:id', to: 'payments#destroy', as: 'payment'
  get '/payments/:return_token/confirm', to: 'payments#confirm', as: 'payment_confirm'
  get '/payments/:id/accept', to: 'payments#accept', as: 'payment_accept'
  get '/payments/:id/refund', to: 'payments#refund', as: 'payment_refund'

  # private payments
  resources :private_payments

  # charges
  resources :charges
  post '/charge_succeed' => 'charges#succeed'

  namespace :api, defaults: {format: :json} do
    resource :auth, controller: :auth, only: [] do
      get :login, on: :collection
    end
    resource :dashboard, controller: :dashboard, only: [] do
      get :counts, on: :collection
    end
    resources :properties, only: [:index]
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base

  belongs_to :landlord, class_name: 'User', foreign_key: :user_id
  belongs_to :contract
  belongs_to :property

  STATUS_UNPAID = 'Unpaid'
  STATUS_PAID = 'Paid'
  STATUS_PENDING = 'Pending'
  STATUS_REFUNDED = 'Refunded'

  PAID_PAYPAL = 'Paypal'
  PAID_CASH = 'Cash'
  PAID_CHEQUE = 'Cheque'

  validates :status, :inclusion => {:in => [STATUS_PAID, STATUS_UNPAID, STATUS_PENDING, STATUS_REFUNDED]}
  validates :paid_type, :inclusion => {:in => [nil, PAID_PAYPAL, PAID_CASH, PAID_CHEQUE]}

  scope :paid, -> { where(status: STATUS_PAID) }
  scope :pending, -> { where(status: STATUS_PENDING) }
  scope :refunded, -> { where(status: STATUS_REFUNDED) }
  scope :outstanding, -> { where(status: STATUS_UNPAID) }
  scope :year, lambda { |year| where('extract(year from due_date) = ?', year) }
  scope :overdue, -> { where('due_date < ?', Date.today) }
  scope :due_soon, -> { where('DATEDIFF(payments.due_date, NOW()) < 4') }

  def paid?
    self.status == STATUS_PAID
  end

  def pending?
    self.status == STATUS_PENDING
  end

  def outstanding?
    self.status == STATUS_UNPAID
  end

  def precise_amount
    '%.2f' % amount
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  before_filter :authenticate_user!

  def outstanding
    if landlord?
      @all_payments = Payment.joins(:contract)
                             .where('contracts.landlord_id = ?', current_user.id)
                             .order(:contract_id, :due_date)
    else
      @all_payments = Payment.joins(:contract)
                             .where('contracts.tenant_id = ?', current_user.id)
                             .order(:contract_id, :due_date)
    end
    @outstanding_payments = @all_payments.outstanding.all + @all_payments.refunded.all
  end

  def paid
    if landlord?
      @all_payments = Payment.joins(:contract)
                             .where('contracts.landlord_id = ?', current_user.id)
                             .order(:contract_id, :due_date)
    else
      @all_payments = Payment.joins(:contract)
                             .where('contracts.tenant_id = ?', current_user.id)
                             .order(:contract_id, :due_date)
    end
    @paid_payments = @all_payments.paid.all + @all_payments.pending.all
  end

  def confirm
    @payment = Payment.find_by_return_token params[:return_token]
    payment_method = params[:payment_method] || @payment.paid_type || Payment::PAID_CASH

    @payment.paid_type = payment_method
    @payment.date_refunded = nil
    if landlord?
      @payment.status = Payment::STATUS_PAID
      @payment.date_accepted = Time.now
    elsif tenant?
      @payment.status = Payment::STATUS_PENDING
    end
    @payment.date_paid = Time.now

    if @payment.save
      UserMailer.tenant_paid_email(@payment).deliver
      redirect_to paid_payments_path, notice: 'Payment is successfully paid.'
    else
      redirect_to outstanding_payments_path, alert: 'Failed to pay.'
    end
  end

  def accept
    @payment = Payment.find params[:id]

    @payment.status = Payment::STATUS_PAID
    @payment.date_accepted = Time.now
    @payment.date_paid ||= Time.now
    @payment.paid_type ||= Payment::PAID_CASH

    if @payment.save
      UserMailer.payment_success_email(@payment).deliver
      UserMailer.landlord_accept_email(@payment).deliver
      redirect_to paid_payments_path, notice: 'Payment is successfully accepted.'
    else
      redirect_to paid_payments_path, alert: 'Failed to accept payment.'
    end
  end

  def refund
    @payment = Payment.find params[:id]

    @payment.status = Payment::STATUS_REFUNDED
    @payment.date_refunded = Time.now

    if @payment.save
      redirect_to paid_payments_path, notice: 'Payment is successfully refunded.'
    else
      redirect_to paid_payments_path, alert: 'Failed to refund payment.'
    end
  end

  def destroy
    @payment = Payment.find params[:id]
    @payment.destroy

    redirect_to outstanding_payments_path, notice: 'Payment is successfully deleted.'
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper

  def paypal_url(payment, return_url)
    email = payment.contract.landlord.paypal_email
    email = payment.contract.landlord.email if email.blank?
    currency = payment.contract.landlord.currency
    currency = 'gpb' if currency.blank?
    values = {
        # get it form your http://sandbox.paypal.com account
        :business => email,
        :cmd => '_cart',
        :upload => 1,
        :return => return_url,
        :invoice => payment.id,
        :amount_1 => payment.amount,
        :currency_code => currency.upcase,
        :item_name_1 => 'GenieLets Rent Invoice ID: ' + payment.id.to_s,
        :item_number_1 => 'For Due Date: ' + payment.due_date.to_s,
        :quantity_1 => 1
    }
    "https://www.paypal.com/cgi-bin/webscr?" + values.to_query
  end

end

app/views/payments/outstanding.html.haml
.row
  .col-sm-12
    .page-header
      %h1
        Payment Dues
        %small Manage Payments

.row
  .col-md-12
    = render 'shared/messages'
    .panel.panel-default
      .panel-heading
        %i.fa.fa-external-link-square
        Outstading Payments
        .panel-tools
          %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
          %a.btn.btn-xs.btn-link.panel-refresh{:href => "#"}
            %i.fa.fa-refresh
      .panel-body
        %table#outstanding-payments-table.table.table-striped.table-bordered.table-hover.table-full-width
          %thead
            %tr
              %th= inverse_user_type.humanize
              %th Invoice ID
              %th Due Date
              %th Amount
              %th Status
              %th Pay Date
              - if landlord?
                %th Actions
              - elsif tenant?
                %th Payments
          %tbody
            - @outstanding_payments.each do |p|
              - if p.contract.connection.approved
                %tr
                  - if landlord?
                    %td= p.contract.tenant_info(current_user)[:name]
                  - elsif tenant?
                    %td= p.contract.landlord.name
                  %td= p.id
                  %td= p.due_date
                  %td= p.precise_amount
                  %td= p.status
                  %td= p.contract.pay_date
                  - if landlord?
                    %td
                      - if p.paused
                        %span You payment is paused.
                        %br
                        %span Please
                        = link_to 'upgrade', account_summary_path
                        %span subscription plan.
                      - else
                        = link_to payment_accept_path(p), class: 'btn btn-primary' do
                          %i.fa.fa-pencil
                          Mark as Paid
                        = link_to payment_path(p), class: 'btn btn-danger', method: :delete, 'data-confirm' => 'Are you sure?' do
                          %i.fa.fa-times
                  - elsif tenant?
                    %td
                      = link_to paypal_url(p, payment_confirm_url(p.return_token, payment_method: Payment::PAID_PAYPAL)),
                                data: {:confirm => 'Refunds via paypal are to be dealt with directly with the tenant, GenieLets cannot offer refunds, click OK to proceed.'} do
                        = image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif")
                      = link_to 'Cash', payment_confirm_path(p.return_token, payment_method: Payment::PAID_CASH), class: 'btn btn-primary',
                                data: {:confirm => 'Refunds via cash are to be dealt with directly with the tenant, GenieLets cannot offer refunds, click OK to proceed.'}
                      = link_to 'Cheque', payment_confirm_path(p.return_token, payment_method: Payment::PAID_CHEQUE), class: 'btn btn-primary',
                                data: {:confirm => 'Refunds via cheque are to be dealt with directly with the tenant, GenieLets cannot offer refunds, click OK to proceed.'}

app/views/payments/paid.html.haml
.row
  .col-sm-12
    .page-header
      %h1
        Paid Payments
        %small Manage Payments

.row
  .col-md-12
    = render 'shared/messages'
    .panel.panel-default
      .panel-heading
        %i.fa.fa-external-link-square
        Paid Payments
        .panel-tools
          %a.btn.btn-xs.btn-link.panel-collapse.collapses{:href => "#"}
          %a.btn.btn-xs.btn-link.panel-refresh{:href => "#"}
            %i.fa.fa-refresh
      .panel-body
        %table#paid-payments-table.table.table-striped.table-bordered.table-hover.table-full-width
          %thead
            %tr
              %th= inverse_user_type.humanize
              %th Invoice ID
              %th Due Date
              %th Amount
              %th Status
              %th Paid Date
              %th Accepted Date
              %th Refunded Date
              %th Payment Type
              - if landlord?
                %th Actions
          %tbody
            - @paid_payments.each do |p|
              %tr
                - if landlord?
                  %td= p.contract.tenant_info(current_user)[:name]
                - elsif tenant?
                  %td= p.contract.landlord.name
                %td= p.id
                %td= p.due_date
                %td= p.precise_amount
                %td= p.status
                %td= p.date_paid
                %td= p.date_accepted
                %td= p.date_refunded
                %td= p.paid_type
                - if landlord?
                  %td
                    - if p.paused
                      %span You payment is paused.
                      %br
                      %span Please
                      = link_to 'upgrade', account_summary_path
                      %span subscription plan.
                    - else
                      - if p.pending?
                        = link_to payment_accept_path(p), class: 'btn btn-primary' do
                          %i.fa.fa-pencil
                          Accept Payment
                      - elsif p.paid?
                        = link_to payment_refund_path(p), class: 'btn btn-danger' do
                          %i.fa.fa-pencil
                          Mark as Refund